### ISSUE TITLE
Syntax Error during compile

### ISSUE THREAD

**Issue by schubox** [kianoshp/SASS-CSS-Boilerplate#1]
From the normalize.css file:

Syntax error: Undefined mixin 'normalizeFont'.
        on line 46 of css/sass/normalize.scss, in `normalizeFont'
        from line 46 of css/sass/normalize.scss

46:     @include normalizeFont;

**Comment by kianoshp** [comment]
Thanks, I will take a look at this. 

Cheers,

Kianosh

**Comment by kianoshp** [comment]
I ran this through the sass compiler and do not get the same error. Did you clone the whole repo and are you using all the partials? This is looking for the 

``` css
@mixin normalizeFont {
    font-family: $fontFamily; 
    color: $fontColor; 
}
```

Which is in the 'partials/_normalize-mixins.scss'. Let me know if you still are encountering the issue and we can set up a chat to talk about it.
